---
- name: <r_oracle_login_t_common> remove origin glogin.sql
  file:
    path: "{{ oracle_home }}/sqlplus/admin/glogin.sql"
    state: absent

- name: <r_oracle_login_t_common> create ORALCE_HOME/login
  file:
    path: "{{ oracle_home }}/login"
    state: directory
    owner: oracle
    group: oinstall
    mode: "0775"

- name: <r_oracle_login_t_common> copy a file to ORACLE_HOME/login/glogin.sql
  copy:
    src: glogin.sql
    dest: "{{ oracle_home }}/login/glogin.sql"
    owner: oracle
    group: oinstall
    mode: "0644"
    #backup: yes
    #validate:

- name: <r_oracle_login_t_common> create two symbolic links
  file:
    src: "{{ oracle_home }}/login/glogin.sql"
    dest: "{{ item }}"
    owner: oracle
    group: oinstall
    mode: "0644"
    state: link
  loop: "{{ glogin_link_targets }}"
