---
- name: <pr_r_hostname_t_common> set system's hostname
  hostname:
    name: "{{ hostname }}" # required. Name of the host

- name: <pr_r_hostname_t_common> add system's hostname line to /etc/hosts
  lineinfile:
    path: /etc/hosts
    state: present
    insertafter: EOF
    line: |-
      {{ ansible_facts['default_ipv4']['address'] }} {{ hostname }}
    #backup: yes

