---
- name: <r_mount_points_t_common> mount up data volumes
  mount:
    path: "{{ v.point }}"
    src: "LABEL={{ v.volume }}"
    fstype: xfs
    state: mounted
  loop: "{{ mount_map | dict2items }}"
  vars:
    v: "{{ item.value }}"

- name: <r_mount_points_t_common> change mount points permission
  file:
    path: "{{ v.point }}"
    state: directory
    owner: oracle
    group: oinstall
    mode: "0775"
  loop: "{{ mount_map | dict2items }}"
  loop_control:
    label: "{{ v.point }}"
  vars:
    v: "{{ item.value }}"
